services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  PowerCaptcha\Typo3\:
    resource: '../Classes/*'
  PowerCaptcha\Typo3\Service\TokenVerification:
    public: true